services:
  - type: web
    name: flask-water-sensors
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "main:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
